### ISSUE TITLE
Select Roast Function | Not Working

### ISSUE THREAD

**Issue by nicholasmackey** [nikmackey/coffee-project#2]
@jacobrhensley 

Select Roast Function | Not Working

After the call, the roast function doesn't seem to work. I haven't had a chance to look over it yet.

Maybe check it out when you have some free time. I'll check it out tomorrow to see if there is anything I can figure out.

![output](https://user-images.githubusercontent.com/59402742/86983846-920c9a80-c152-11ea-8ac2-4accb5d3371e.png)

**Comment by jacobrhensley** [comment]
I took a look at it and couldn't quite get it tonight. I'll look again tomorrow.
